[chips]
"at" = "at"
"it" = "it"
"in" = "in"
"is" = "is"
"of" = "of"
"to" = "to"
"so" = "so"
"be"= "be"
"into" = "into"
"do" = "do"
"us" = "us"
"an" = "an" 
"by" = "by"
"up" = "up"
"or" = "or"
"go" = "go"
"he" = "he"
"me" = "me"
"if" = "if"
"we" = "we"
"as" = "as"

"his" = "his"
"now" = "now"

"i" = "I"

"o" = "on"
"n" = "no"
"js" = "just"
"nv" = "never"
"pl"= "people"
"t" = "the"
"ad" = "and"
"y" = "you"
"th" = "that"
"f" = "for"
"bu" = "but"
"ma" = "my"
"ar" = "are"
"nt" = "not"
"yr" = "your"
"al" = "all"
"hv" = "have"
"aw" = "was"
"wht" = "with"
"ts" = "this"
"wt" = "what"
"ty" = "they"
"wn" = "when"
"cn" = "can"
"kw" = "know"
"oe" ="one"
"tr" = "there"
"lk" = "like"
"wi" = "will"
"ig" = "it's"
"dn" = "don't"
"im" = "I'm"
"iv" = "I've"
"lf" = "life"
"frm" = "from"
"tm" = "time"
"ow" = "who"
"ou" = "out"
"et" = "them"
"ab" = "about"
"mr" = "more" 
"yo" = "you're"
"hd" = "had"
"ur" = "our"
"ly" = "only"
"hw" = "how"
"tg" = "thing"
"g" = "get"
"eg" = "enough"
"se" = "see"
"wul" = "would"
"rw" = "were"
"wor" = "word"
"wrl" = "world"
"lv" = "live"
"ov"  = "love"
"jt"  = "than"
"ei" = "their"
"bj" = "because"
"bk" = "back"
"bl" = "black"
"bh" = "behind"
"bo" = "before"
"tk"= "think"
"mk" = "make"
"en"= "then"
"sm" = "some"
"sg" = "something"
"bn" = "been"
"ej" = "end"
"ev" ="even"
"wy" = "way"
"ghs" = "things"
"hm" = "him"
"cu" = "could"
"wnt" = "want"
"dy" = "day"
"hs" = "has"
"oj" = "other"
"aj" = "another"
"dif" = "different"
"ys" = "yes"
"ye"  = "you're"
"b" = "be"
"yv" = "you've"
"d" = "and"
"di"  = "did"

